### ISSUE TITLE
Can this be made into a package?

### ISSUE THREAD

**Issue by GanZhiXiong** [javiercbk/json_to_dart#47] opened 2019-12-13 07:42 UTC
You can make this into a package, and when you add your package to the flutter project, you create a json file that you want to generate the dart class, and then type the generate command at the terminal to generate the corresponding dart class file

😂I do not know if there is a package with similar functions, I am looking forward to it!!

**Comment by javiercbk** [comment] 2019-12-13 12:31
Duplicate of #6

**Closed by javiercbk** 2019-12-13 12:31 UTC
